name: Deploy on push to master
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer update --ignore-platform-reqs --no-dev

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Zip vendor
        run: zip vendor.zip vendor composer.json composer.lock -r && rm -rf vendor

      - name: Zip public
        run: cd public && zip public.zip -r * ".htaccess" && ls -QA | grep -v public.zip | xargs rm -rf && ls -l

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.LARAVEL_SITE_SERVER }}
          username: ${{ secrets.LARAVEL_SITE_USER }}
          password: ${{ secrets.LARAVEL_SITE_PASS }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            composer.json
            composer.lock
